### PR TITLE
MPU Code and General Documentation/Onboarding for New Members

### PR DESCRIPTION
**Pull request by nwdepatie**

### CODE REVIEW

**Comment by nwdepatie** [comment]
Code works, but I might sift through and clean up code a bit

**Comment by nwdepatie** [comment]
Looking specifically for what else to add to documentation/onboarding that might be helpful

**Review by mccauleyma — APPROVED** [review]
All looks pretty good! Did not really review the code, just the readMe and stuff since the code will be tested on car. What's the deal with the repos? Did you go back to using submodules again??

**Review by rydzynskip — APPROVED** [review]
Looks good, also didn't really review the actual code, just gave a look over. My only comments based on the architecture picture was that it seems a little bit too interconnected. The pedal box, gpio, and driverio class probably could be simplified/refactored to where they don't reference the MC and BMS objects, and instead the MPU would be doing all the control code. All of the side classes should be pretty short and localized and then the MPU should be a longer, more complicated class connecting everything. This would make debugging more central (no need to over abstract).  Just a future consideration for updates though.

**Pull request merged**
