### PR TITLE
#42 Can message for SD Status and Accelerometer

### LINKED ISSUE #42: Send GFORCE data from TCU
DO IT!

### PR DESCRIPTION
**Pull request by Peyton-McKee**
sending can message for SD Status and accelerometer 

closes #42

### CODE REVIEW

**Review by mccauleyma — COMMENTED** [review]
Seems like it could work 🤷 Should be tested first tho maybe

**Comment by rydzynskip** [comment]
I already had the SD status functional on my GPS testing PR. My fault for not merging it sooner. It's using the LoggerStatus() function instead of the init status so we can detect if a change in the logging occurs after initialization.

I'll add the line to send the CAN message and then merge it in.

**Comment by mccauleyma** [comment]
And can add accelerometer sending?

**Comment by Peyton-McKee** [comment]
Completed by peter in his PR

**Pull request closed without merging**
